### PR TITLE
Add GFX908 specific HCC changes

### PR DESCRIPTION
**Pull request by aaronenyeshi**
GFX908 has completed upstream into llvm and clang.

### CODE REVIEW

**Comment by scchan** [comment]
we also need a change in clang driver?  https://github.com/RadeonOpenCompute/hcc-clang-upgrade/blob/ba1c0486eb104cc37f88e322296bd67adc58ad4a/lib/Driver/ToolChains/Hcc.cpp#L175

**Comment by aaronenyeshi** [comment]
Thanks, I just pushed that clang change: https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/180

**Comment by scchan** [comment]
I merged the clang PR, could you update the clang submodule in this PR to pick that up?

**Comment by aaronenyeshi** [comment]
Thanks! I just updated the clang submodule

**Review by scchan — APPROVED** [review]

**Pull request merged**
