### PR TITLE
Add Function Call Support for HCC by flag

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Pass into hcc command arg -amdgpu-function-calls to enable function call support. This flag will be consumed by clang, and passed into linker. Linker will handle function call support, and pass correctly into LLC and SAC pass. This Flag will allow the user to toggle on/off FCS.

We need to first merge these PRs to clang and llvm.
https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/168
https://github.com/RadeonOpenCompute/llvm/pull/159

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
Before we update the submodule, I think we need to wait for Merge maintanence issues to resolve. Seems there is a lot of delta in llvm and clang from Feb 26 to now.

**Comment by david-salinas** [comment]
> Before we update the submodule, I think we need to wait for Merge maintanence issues to resolve. Seems there is a lot of delta in llvm and clang from Feb 26 to now.

I'm working on getting an upstream merge PR.  There is one from this morning, but it is with a clang with upstream changes from friday, and llvm has moved on since then such that that clang is already out dated ... sigh.  There has been a delay in getting an upstream merge because of changes to amdgpu attributes broke our old and outdated HCC amdgpu attributes.

**Comment by aaronenyeshi** [comment]
Thanks @david-salinas , ping me once the upstream merge is in. Then we can move forward to adding this change

**Comment by rocm-hcc** [comment]
> Thanks @david-salinas , ping me once the upstream merge is in. Then we can move forward to adding this change

@aaronenyeshi  I merged https://github.com/RadeonOpenCompute/hcc/pull/1064 last night.  Sorry I forgot to ping you sooner.

**Comment by aaronenyeshi** [comment]
Since HCC PR https://github.com/RadeonOpenCompute/hcc/pull/1065 has merged, the submodule dependencies for this PR are linked now: https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/170 https://github.com/RadeonOpenCompute/llvm/pull/159 https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/168

**Comment by scchan** [comment]
Could you add a test for this switch?

**Comment by aaronenyeshi** [comment]
Is this preliminary test OK? We can develop more tests in that directory hcc/tests/Unit/FunctionCall/

**Review by scchan — APPROVED** [review]
LGTM

**Pull request merged**
