### PR TITLE
[Config] revise submodule configuration

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by scchan** [comment]
could you provide results from make test?

**Comment by yxsamliu** [comment]
There are some failures due to last merge.

[result.170803c.txt](https://github.com/RadeonOpenCompute/hcc/files/1198117/result.170803c.txt)

**Comment by scchan** [comment]
@yxsamliu just wondering if you have any insights on regression in atomic tests, are they related to syncscope?

**Comment by yxsamliu** [comment]
I guess so, but I need investigation.

**Comment by whchung** [comment]
Merged based on the consent with @yxsamliu .

**Pull request merged**
