### PR TITLE
cmake: Use ${CMAKE_INSTALL_LIBDIR} consistently

### PR DESCRIPTION
**Pull request by jvesely**
Fixes build on fedora where .so libs were installed in 'lib64' but hcc-config pointed to 'lib'
Also fix clang builtin location

Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

### CODE REVIEW

**Comment by scchan** [comment]
#261 also covers this, could you take a look?

**Comment by jvesely** [comment]
yeah, e039e9724 works for me.
It misses the includedir change, though.

**Comment by scchan** [comment]
The include path is set here and it is not using CMAKE_INSTALL_INCLUDEDIR https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/include/CMakeLists.txt#L3

**Comment by jvesely** [comment]
right, I stand corrected.
thanks

**Pull request closed without merging**
