### PR TITLE
Test math functions as well

### PR DESCRIPTION
**Pull request by pfultz2**

### CODE REVIEW

**Review by whchung — APPROVED** [review]
LGTM

**Comment by scchan** [comment]
This PR incorrectly changed clang and llvm to point to older commits

**Comment by scchan** [comment]
I submitted a PR to revert the clang and llvm change  
https://github.com/RadeonOpenCompute/hcc/pull/214
@whchung  could you take a look?

**Comment by whchung** [comment]
@scchan Thanks, I've merged #214 .

**Pull request merged**
