### PR TITLE
Workaround AMDGPU backend stability isue in SI waitcnt insertion pass

### PR DESCRIPTION
**Pull request by whchung**
It has been observed some workloads have trouble in SI waitcnt insertion pass
in AMDGPU backend. In this commit we temporarily disable using the pass.

### CODE REVIEW

**Review by scchan — COMMENTED** [review]
It's fine that we disable it temporary but is there a ticket opened against the backend for the stability issue?

**Comment by whchung** [comment]
@scchan developers working on AMDGPU backend are notified

**Review by scchan — APPROVED** [review]

**Comment by scchan** [comment]
@whchung do we need this in 1.6?

**Comment by whchung** [comment]
@scchan no it's not required

**Pull request merged**
