### PR TITLE
Define const member function if needed

### PR DESCRIPTION
**Pull request by facao**
We define void* as the handle of i.e. queue, device, etc. And internally, it is a pointer to class member.

1. We will expose class member to outside, but good news is, we expose void*, and does not expose its  data type.

2. Make it hard to define getter method to const, because it also needs to declare the return value to be const too, then, cast from "a pointer to a constant member" to void*, which will also request const_cast.

In this change, only change what is easy, and for others, we may need to change the architect, which is not expected I believe.

### CODE REVIEW

**Comment by whchung** [comment]
@facao in order to ensure integrity of the compiler, could you help provide result of:

- ```HCC_RUNTIME=HSA make test```
- HIP uni test results

**Comment by whchung** [comment]
@facao any updates on this?

**Comment by whchung** [comment]
@facao I'll take this pull request without test results as it does seem harmless. But for API changes I would generally ask for:

- result of HCC unit tests "HCC_RUNTIME=HSA make test"
- result of HIP unit tests

You can refer to other pull requests for more examples.

**Comment by facao** [comment]
I will make up the Unit tests asap later, my local system is occupied fully recently.

**Comment by yan-ming** [comment]
Hi @facao , this PR doesn't seem to be smooth on my end, could you verify my failings on your system?

I'm on 836266.

```
********************
Testing Time: 634.12s
********************
Failing Tests (29):
    CPPAMP :: Unit/AmpShortVectors/hc_short_vector_device.cpp
    CPPAMP :: Unit/GridLaunch/accelerator_view.cpp
    CPPAMP :: Unit/GridLaunch/char_argument.cpp
    CPPAMP :: Unit/GridLaunch/completion_future.cpp
    CPPAMP :: Unit/GridLaunch/customtype_byptr.cpp
    CPPAMP :: Unit/GridLaunch/customtype_byval.cpp
    CPPAMP :: Unit/GridLaunch/customtype_byval_char.cpp
    CPPAMP :: Unit/GridLaunch/glp_const.cpp
    CPPAMP :: Unit/GridLaunch/glp_typedef.cpp
    CPPAMP :: Unit/GridLaunch/hc_attr.cpp
    CPPAMP :: Unit/GridLaunch/linkobj.cpp
    CPPAMP :: Unit/GridLaunch/rect_tiles.cpp
    CPPAMP :: Unit/GridLaunch/union.cpp
    CPPAMP :: Unit/HC/memcpy_symbol1.cpp
    CPPAMP :: Unit/HC/memcpy_symbol3.cpp
    CPPAMP :: Unit/HC/placement_new.cpp
    CPPAMP :: Unit/HC/test1.cpp
    CPPAMP :: Unit/HC/test3.cpp
    CPPAMP :: Unit/HC/test4.cpp
    CPPAMP :: Unit/HC/test7.cpp
    CPPAMP :: Unit/HC/test8.cpp
    CPPAMP :: Unit/HC/tick2.cpp
    CPPAMP :: Unit/HC/wg_size.cpp
    CPPAMP :: Unit/HSA/printf.cpp
    CPPAMP :: Unit/HSAIL/shfl_xor.cpp
    CPPAMP :: Unit/Pool/map_to_peers_device_ptr.cpp
    CPPAMP :: Unit/Pool/map_to_peers_host_ptr.cpp
    CPPAMP :: Unit/SharedLibrary/shared_library2.cpp
    CPPAMP :: Unit/SharedLibrary/shared_library3.cpp

  Expected Passes    : 642
  Expected Failures  : 25
  Unsupported Tests  : 10
  Unexpected Failures: 29

```

**Comment by whchung** [comment]
@yan-ming Yes, I noticed this too. HIP tests are also failing on my side. I've reverted commits from this PR.

**Comment by facao** [comment]
@yan-ming @whchung  there is a header added by mistake in hc.hpp I think, will pull an new request after verifying with Unit/HIP tests. BTW, which branch you are working on? I even got Unit test error without the change.

**Comment by whchung** [comment]
@facao I'm using develop branch, and with HSAIL backend. On LC backend I can still see some more failed cases which still need to be addressed.

**Comment by yan-ming** [comment]
@facao I was on 8362669 where the merge point of this PR and develop branch.

**Pull request merged**
