### PR TITLE
[Config] revise submodule configuration for 20171003 merge

### PR DESCRIPTION
**Pull request by whchung**
updated `make test` result:

```
********************
Testing Time: 442.47s
********************
Failing Tests (4):
    HCC :: Unit/DynamicTileStatic/test11.cpp
```

### CODE REVIEW

**Comment by whchung** [comment]
@scchan @kknox how should i force a CI test build?

**Comment by scchan** [comment]
@whchung go to the Jenkins server --> login, then go to your PR and you should find an option called "Build with Parameters".

**Comment by scchan** [comment]
@whchung   Except for Unit/DynamicTileStatic/test11.cpp, which will be fixed by rocdl, the other ones seem to be recent regressions.  Could you investigate what cause those regressions?

**Comment by whchung** [comment]
@scchan the other 3 failed seems to be related to having multiple kernel dumps. I'll fix the tests to explicitly specify 1 AMDGPU target and do FileCheck on that particular kernel dump.

**Comment by whchung** [comment]
@scchan the PR has been updated and passed CI check, also I've updated `make test` result. please kindly review again. thanks.

**Review by scchan — APPROVED** [review]

**Pull request merged**
