### PR TITLE
Revert Combine opt invocations in clamp-device

### PR DESCRIPTION
**Pull request by aaronenyeshi**
This is meant to fix a rocPRIM unit test failure: rocprim.hc.device_scan

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
This commit partially reverts commit: https://github.com/RadeonOpenCompute/hcc/commit/05f3bcc682ea1446ae6c50660383d54806ad4149

**Comment by david-salinas** [comment]
Does the change in clamp-link.in also need to be reverted, or just clamp-device.in ?

**Comment by aaronenyeshi** [comment]
Just the clamp-device.in change will fix the failure

**Comment by aaronenyeshi** [comment]
The root cause is that -O3 will change the structure of custom passes. So when we combined the -O3 argument with our two custom passes, the custom passes stop working as intended. Addition pre-pass and post-pass optimizations are added to our custom passes which causes a big discrepancy in LLVM IR

**Review by david-salinas — APPROVED** [review]
LGTM

**Review by scchan — APPROVED** [review]
LGTM

**Pull request merged**
