### PR TITLE
Update submodule commits for May 23 amd-common merge

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by whchung** [comment]
@yxsamliu I've merged your other PRs to `llvm` and `hcc-clang-upgrade` but couldn't get this one in due to merge conflicts. could you help resolve them? Thanks.

**Comment by yxsamliu** [comment]
ldd also needs merge https://github.com/RadeonOpenCompute/lld/pull/13

**Comment by whchung** [comment]
@yxsamliu thanks for notification. just merged RadeonOpenCompute/lld#13

**Comment by scchan** [comment]
could we also update compiler-rt?

**Comment by yxsamliu** [comment]
I am going to update it. I think the failure may be due to I used commits in my own branch.

**Comment by scchan** [comment]
I think you'll have to resolve the conflicts first (probably because the commits to the submodule have changed since your created your branch).  I'd suggest doing a merge from clang_tot_upgrade into your own branch and then confirm to git that we are going to use the newer commits for the submodules.

**Comment by yxsamliu** [comment]
right.

**Comment by yxsamliu** [comment]
It seems changing rocdl branch to master caused atomic unit tests to fail. It seems the sed script for changing the address space was not run in the rocdl master branch.

**Comment by whchung** [comment]
@yxsamliu relevant codes in ROCDL could be found at https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/remove-promote-change-addr-space/CMakeLists.txt#L22 , compare it with https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/CMakeLists.txt it seems there are some subtle differences...

**Comment by scchan** [comment]
I don't see any failure with atomics with the latest rocdl master though

**Comment by yxsamliu** [comment]
After I clean my rocdl diretory and rebuild, the issue disappeared.

About compiler-rt, there is no update from the RadeonOpenCompute/compiler-rt.git master branch.

**Comment by scchan** [comment]
@whchung   The PR could be built now so we could merge it?  The CI failure is unrelated to this code change.

**Pull request merged**
