### PR TITLE
Change rocdl branch to master and update submodule commits after merg…

### PR DESCRIPTION
**Pull request by yxsamliu**
…ing with amd-common

### CODE REVIEW

**Review by whchung — CHANGES_REQUESTED** [review]
@yxsamliu Could you change `Jenkinsfile` so it git clone from `master` branch as well? It seems `Jenkinsfile` is written to use `git clone --recursive` or `git submodule update` , but `git clone` individual components with fixed branch name.

**Comment by scchan** [comment]
This is a dup of https://github.com/RadeonOpenCompute/hcc/pull/321

**Comment by whchung** [comment]
@scchan this PR contains changes to `.gitmodules` . does #321 has the same thing? if yes we can close this one

**Comment by scchan** [comment]
@whchung  updated .gitmodule for the rocdl branch:   https://github.com/RadeonOpenCompute/hcc/pull/321/commits/3d8d1c2105597877f2586e7c3b1bff6583f184e4

**Comment by whchung** [comment]
close this PR per comment from @scchan

**Pull request closed without merging**
