### PR TITLE
enable short vector for half fp

### PR DESCRIPTION
**Pull request by scchan**

### CODE REVIEW

**Review by whchung — CHANGES_REQUESTED** [review]
@scchan could you add unit tests for this PR? Or change existing tests and add new function templates?

**Comment by scchan** [comment]
sure, will add half precision short vector tests

**Comment by kknox** [comment]
Just a reminder, if you add unit tests, you should add logic to [run the tests in the jenkinsfile](https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/Jenkinsfile#L82) so that unit tests are considered part of a successful build

**Comment by scchan** [comment]
@whchung I modified an existing test to include half and created a new unit test with half

**Comment by scchan** [comment]
@whchung I added new tests as you suggested, could you review this again?  thanks

**Review by whchung — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
