### PR TITLE
Improve the exit code output to show file and line number

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Add a new function to handle the exit codes, and give more information as to exit location.

### CODE REVIEW

**Review by scchan — COMMENTED** [review]
improving clamp-assemble seems moot since it won't get used after https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/165
are there other scripts that could be improved by exit_with_code()?

**Comment by aaronenyeshi** [comment]
Oh right, I had made the changes locally to all the assemble scripts, but some reason only added one with `git add`. Let me force update this commit

**Comment by aaronenyeshi** [comment]
Please check the updated commit, which includes the hc-kernel-assemble and hc-host-assemble

**Review by scchan — APPROVED** [review]
LGTM

**Pull request merged**
