### PR TITLE
Fixed unpinned copy mode issue

### PR DESCRIPTION
**Pull request by gargrahul**
- Enabled Copy mode selection through env variable
- Guarded PinInPlace logic from being called with already locked pointer.

### CODE REVIEW

**Comment by scchan** [comment]
@gargrahul  Please resolve the merge conflict.  Note that your previous unpinned copy patch was pull out due to test regressions

**Review by scchan — CHANGES_REQUESTED** [review]
resolve merge conflict

**Review by whchung — CHANGES_REQUESTED** [review]
@gargrahul as @scchan suggests, please help fix merge conflicts. you may want to rebase with clang_tot_upgrade branch beforehand.

**Comment by scchan** [comment]
There's a still a merge conflict (rocdl) and this PR is pulling in commits from others.  I'd suggest that you rebase your patch and submit your patch in new PR.

**Pull request closed without merging**
