### PR TITLE
cmake refactoring

### PR DESCRIPTION
**Pull request by dfukalov**
1. combined install dirs 'bin' and 'compiler/bin'
2. explicit llvm+clang compiler' cmake+make invoke replaced with add_subdirectory()
3. reduced package size
4. minor improvements

### CODE REVIEW

**Comment by whchung** [comment]
@dfukalov thanks. this PR looks much more concise.

**Comment by pfultz2** [comment]
I think this will affect the clang-tidy building as well in PR #369. It looks like with this new pull request it won't build clang-tidy anymore.

**Comment by dfukalov** [comment]
Yes, there is a conflict in changes here. And I guess github will report it for second of us.
I can update my branch once your PR will be merged in, it's not an issue.

@whchung,  would you please advise who's going first?

**Comment by whchung** [comment]
@dfukalov I think I'm leaning toward getting @pfultz2 's PR in first.

**Comment by dfukalov** [comment]
Ok, I'll wait for merge of PR #369

**Review by whchung — APPROVED** [review]

**Pull request merged**
