### PR TITLE
Move amdgcn intrinsics from hc.amdgcn.ll to hc.hpp

### PR DESCRIPTION
**Pull request by david-salinas**
This is a minimal fix to get the known issues resolved. For a complete fix, we'd move all of the intrinsics in hc.amdgcn.ll from device-libs here.

### CODE REVIEW

**Review by arsenm — CHANGES_REQUESTED** [review]
This still isn't using the clang builtins. This should use the __builtin_amdgcn_* builtins, and not use asm declarations

**Comment by b-sumner** [comment]
I agree with Matt. This should use the clang builtins, and switch to update.dpp from mov.dpp.

**Comment by david-salinas** [comment]
My latest commit, is just to get the known failing tests passing.  I'm working on the remaining functions in hc.amdgcn.ll, which I'll have early next week.

**Comment by david-salinas** [comment]
@b-sumner and @arsenm , so using the builtins is an issue for HCC.  Because HCC invokes clang without specifying a  target, clang flags the use of the DPP builtins without enabling the DPP feature.  You can see the errors in the HCC build/test Check for this PR: http://hsautil.amd.com/job/RadeonOpenCompute/job/hcc/job/PR-1080/4/console

**Comment by arsenm** [comment]
You need to place the +dpp feature on the calling function, e.g. __attribute__((target("dpp")))

**Comment by b-sumner** [comment]
Sorry, I keep overlooking this serious problem with hcc, and I shouldn't.  We should probably go back and just make the minimal changes to the .ll file or wherever that fix the original problem.

**Comment by david-salinas** [comment]
@scchan @b-sumner @arsenm 
ok, I updated the fix to use __asm again for llvm.amdgcn.update and llvm.amdgcn.ds.swizzle.  When I tried addind the attribute((target("dpp"))) I got a warning indicating that "dpp" is invalid for the target attribute, and it would be ignored.  The check just ran and all tests passed.

**Review by scchan — APPROVED** [review]
I think we'll settle with this workaround for now.  LGTM

**Pull request merged**
