### PR TITLE
initial protyping for std/hc vector

### PR DESCRIPTION
**Pull request by PhilipDeegan**
works with [this example](https://gist.github.com/Dekken/92cfcc313e539e1446f669f5c3cd5324)

my text editor is set up to remove trailing white spaces so sorry about that

I don't specifically like the way this is done as _data/_data_host require a default constructor which may not be the best idea

### CODE REVIEW

**Comment by AlexVlx** [comment]
Hello @Dekken, thank you for the PR. I do have a few concerns - to begin with:
1) what is this trying to solve?
2) choosing the name `vector` is extremely unfortunate, as it'll be extremely clashy (we already suffer this when it comes to `array`) and inculcate the expectation that this IS A `std::vector` which it is not (I've noted the inheritance from `std::vector` which is a faux-pas, as the standard library containers are not intended to be inherited from - observe the absence of a virtual destructor, for example).

**Comment by PhilipDeegan** [comment]
1. vectors are useful.
2. the name is arbitrary, but  I see your point regarding the destructor

**Comment by PhilipDeegan** [comment]
Compile time array sizes are all well and good but not always feasible to know in advance.
Using the "new" operator manually goes against the notions of RAII and thus C style arrays are not always the best choice 

Hence a "vector-like" type would resolve both of these

Renaming the type is not an issue IMO - and as you suggest not inheriting from a standard container is not wise - reject to rework

**Comment by AlexVlx** [comment]
I'm still a bit confused as to what gap you observe - `array_view` interops with `std::` containers, `array` is dynamically sized at runtime (that's another terrible name choice though, if only we could travel through time and make a different one). Where do you need to use `operator new` / why can you not use `array_view` on top of a `std::vector` - perhaps answering these can drive further investigation?

**Comment by PhilipDeegan** [comment]
Yes I see how you can use a std::vector with array_view now, however this is *somewhat* restrictive I think as it requires the vector to be completed populated in order to access the ".size()" to then create the array_view - unless I'm mistaken

I'm just curious as to why you would create a wrapper class if you don't need it

**Comment by PhilipDeegan** [comment]
Updated to use composition and changed the name to "hector" @ https://github.com/0xz/hcc/commit/6e4ae265dc91efca46e07de0ca4e57c7e6fae2af

**Pull request closed without merging**
