### PR TITLE
[Config] revise submodule configuration for alloca merge

### PR DESCRIPTION
**Pull request by scchan**

### CODE REVIEW

**Comment by yxsamliu** [comment]
LGTM

**Review by whchung — APPROVED** [review]
LGTM

**Review by whchung — CHANGES_REQUESTED** [review]
@scchan could you change `Jenkinsfile` so it clone the proper branch?

**Comment by scchan** [comment]
@whchung it builds fine now

**Review by whchung — APPROVED** [review]

**Pull request merged**
