### PR TITLE
replace __hc math functions with __ocml functions

### PR DESCRIPTION
**Pull request by david-salinas**
remove the forward declarations of the __hc_ math functions and call the ocml functions (in rocdl) directly.

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
Thanks David, should we address these comments from https://github.com/RadeonOpenCompute/hcc/pull/865 in another PR? 
```
Instead of type __fp16, please use _Float16.
Some unit tests needed for these _Float16 math functions.
```

**Comment by david-salinas** [comment]
> Thanks David, should we address these comments from #865 in another PR?
> 
> ```
> Instead of type __fp16, please use _Float16.
> Some unit tests needed for these _Float16 math functions.
> ```

I'll make the change to _Float16, that does seem to be what clang recommends.  And adding the type to the tests, will come in an update.  I'll see if I can add it to this PR, otherwise I'll create a separate PR.

**Review by aaronenyeshi — CHANGES_REQUESTED** [review]
Thanks @david-salinas , I'll re-review after you add replace __fp16 with _Float16.

**Comment by david-salinas** [comment]
So, I've changed __fp16 to _Float16.  But I haven't added changes to existing AmpMath tests to test for _Float16 types.  Because we need to add a stdlib that supports the half float type, and right now the stdc++ we use does not.  I'm opening a ticket for myself (SWDEV-173564) to add half float testing to our HCC unit tests.  In the meantime we might as well let these cosmetic changes go in.

**Review by aaronenyeshi — APPROVED** [review]
LGTM

**Pull request merged**
