### PR TITLE
use a smaller async ops vector size to reduce the number of signals

### PR DESCRIPTION
**Pull request by scchan**

### CODE REVIEW

**Comment by scchan** [comment]
@gargrahul could you please review?

**Review by gargrahul — APPROVED** [review]
LGTM

**Comment by jeffdaily** [comment]
How small is too small?  If it is too small, the host will block until the op signal clears.  Have we verified whether this affects performance of benchmarks and frameworks?

**Comment by jeffdaily** [comment]
I can see a small asyncop size like this being okay, but only if we also managed to not allocate a signal for every kernel.  Otherwise, frequent queuing of kernels will block the host.  I am aware of one or more PyTorch workloads that queues many kernels, where we were already seeing the queue depth to be reached when it was still 16K.

**Comment by scchan** [comment]
This PR was closed by mistake and it couldn't be reopen for some reason...

**Pull request closed without merging**
