### PR TITLE
Build and run cmake test on jenkins

### PR DESCRIPTION
**Pull request by pfultz2**

### CODE REVIEW

**Review by whchung — APPROVED** [review]
LGTM

**Comment by whchung** [comment]
@pfultz2 Could you review `Jenkinsfile` and the build log at `http://hsautil.amd.com/job/RadeonOpenCompute/job/hcc/job/jenkins-cmake-test/4/console` to see if the errors met in `make install` are related to this PR?

**Comment by pfultz2** [comment]
> Could you review Jenkinsfile and the build log at http://hsautil.amd.com/job/RadeonOpenCompute/job/hcc/job/jenkins-cmake-test/4/console to see if the errors met in make install are related to this PR?

Yea, I am looking into it.

**Comment by pfultz2** [comment]
So I fixed the install problem.

**Pull request merged**
