### PR TITLE
Add gfx906 - Vega20 Support

### PR DESCRIPTION
**Pull request by aaronenyeshi**

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
Added https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/138

**Review by scchan — APPROVED** [review]
LGTM

**Comment by scchan** [comment]
@aaronenyeshi could you submit the change to support gfx906 in HIP as well?

**Comment by aaronenyeshi** [comment]
@scchan Yes, I will do that

**Comment by aaronenyeshi** [comment]
@scchan Please see HIP change for gfx906 here: https://github.com/ROCm-Developer-Tools/HIP/pull/444

**Pull request merged**
