### PR TITLE
create hsa queue lazily

### PR DESCRIPTION
**Pull request by scchan**

### CODE REVIEW

**Comment by scchan** [comment]
@gargrahul  this prevents hipGetDeviceCount() (or some other HIP APIs) from eagerly creating HSA queues, could you review this?  Thanks

**Comment by jeffdaily** [comment]
This PR looks relatively innocent.  Which issues is this addressing?  Have we validated against frameworks yet?  If you would like, I could try this out on TensorFlow to make sure nothing breaks.  Let me know.

**Comment by gargrahul** [comment]
@jeffdaily This PR should help delaying of creation of HSA resources ONLY on first actual use. So it addresses issue of creating queues with first HIP call when there isn't any actual work being done with that call. For example hipGetDeviceCount => which is a query API.

**Comment by jeffdaily** [comment]
Thank you @gargrahul .  Do we know whether any frameworks have been tested with this PR yet?

**Comment by scchan** [comment]
@jeffdaily No I haven't but will try with Caffe2 and PyTorch tomorrow.

**Comment by scchan** [comment]
my framework tests are still running but a lot of them has already been run without issue and I don't see any regression so far, merging this now

**Pull request merged**
