### PR TITLE
Add clang-tidy submodule

### PR DESCRIPTION
**Pull request by pfultz2**
This will build clang tidy as part of the hcc build.

### CODE REVIEW

**Comment by whchung** [comment]
@pfultz2 could you advise how `clang-tidy` are used in the applications you are working on?

**Comment by pfultz2** [comment]
We run `clang-tidy` in cmake, with this:

```cmake
add_custom_target(tidy
    COMMAND ${CLANG_TIDY_EXE} 
    -p ${CMAKE_BINARY_DIR} 
    -checks='${CLANG_TIDY_CHECKS}'
    ${SOURCES}
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    COMMENT "clang-tidy: Running clang-tidy ..."
)
```

Having it built with hcc allows us to use this for our hip backend, as vanilla clang-tidy can't handle the hcc-specific things.

**Comment by whchung** [comment]
@pfultz2 could you help revise `SYNC_UPSTREAM.md` so it accommodates additional steps required for supporting this submodule? I'll review the steps and take it once other supporting infrastructures are ready.

Also I think there could be other supporting documents / scripts may need to be created in future PRs:
- DEB / RPM scripts
- Jenkinsfile
- Dockerfile

**Review by whchung — APPROVED** [review]
LGTM

**Pull request merged**
