### PR TITLE
disable wg_register_limit1 test until issue is resolved

### PR DESCRIPTION
**Pull request by david-salinas**
Just disabling this test until we resolve the failure.

### CODE REVIEW

**Review by scchan — COMMENTED** [review]
could you add the ticket # for this regression?

**Comment by david-salinas** [comment]
SWDEV-170201

**Comment by scchan** [comment]
I mean adding that to the unit test

**Review by scchan — CHANGES_REQUESTED** [review]
Please include ticket # for this regression

**Review by scchan — APPROVED** [review]
LGTM

**Pull request merged**
