### PR TITLE
Add support for allocating finegrained GPU memory

### PR DESCRIPTION
**Pull request by mangupta**

### CODE REVIEW

**Comment by mangupta** [comment]
Replaces #1075 which had a rebase issue.

**Review by scchan — DISMISSED** [review]
LGTM

**Review by scchan — CHANGES_REQUESTED** [review]
This PR is causing a lot of unit tests to fail, could you validate this patch with `make test` and provide test results?  Thanks
http://hsautil.amd.com/job/RadeonOpenCompute/job/hcc/job/PR-1076/3/consoleFull

**Comment by mangupta** [comment]
All the tests fail due to "No suitable runtime detected. Fall back to CPU!". However I don't see this on my development system. From what I see in the compiler source, this error is reported when we fail to detect ROCr. I will try debugging more on my end by trying on another system as well as trying inside a docker container.

**Review by scchan — APPROVED** [review]

**Pull request merged**
