### PR TITLE
Remove deprecated hsa_signal_wait_acquire function

### PR DESCRIPTION
**Pull request by aaronenyeshi**
New hsa_signal_wait uses function hsa_signal_wait_scaquire.

### CODE REVIEW

**Comment by whchung** [comment]
@aaronenyeshi I believe this PR has been rebased to take advantage of #709 , right?

**Comment by aaronenyeshi** [comment]
@whchung Yes I changed all those in PR 709 into the new functions.

**Review by whchung — APPROVED** [review]
LGTM

**Review by scchan — APPROVED** [review]
LGTM

**Pull request merged**
