### PR TITLE
Add tests to the jenkinsfile

### PR DESCRIPTION
**Pull request by pfultz2**
This will run the tests in the jenkins build.

### CODE REVIEW

**Comment by pfultz2** [comment]
It seems 15 tests have failed:

```
Failing Tests (15):
    HCC :: Unit/AMDGPU/clock.cpp
    HCC :: Unit/AMDGPU/register-control.cpp
    HCC :: Unit/AMDGPU/shfl.cpp
    HCC :: Unit/AMDGPU/shfl_down.cpp
    HCC :: Unit/AMDGPU/shfl_scan.cpp
    HCC :: Unit/AMDGPU/shfl_up.cpp
    HCC :: Unit/AMDGPU/shfl_xor.cpp
    HCC :: Unit/AsyncPFE/async_av_dependent8.cpp
    HCC :: Unit/GridLaunch/register-control.cpp
    HCC :: Unit/HC/amdgcn_ds_bpermute.cpp
    HCC :: Unit/HC/amdgcn_ds_permute.cpp
    HCC :: Unit/HC/amdgcn_wave_rl1.cpp
    HCC :: Unit/HC/amdgcn_wave_rr1.cpp
    HCC :: Unit/HC/amdgcn_wave_sl1.cpp
    HCC :: Unit/HC/amdgcn_wave_sr1.cpp

  Expected Passes    : 705
  Expected Failures  : 30
  Unexpected Failures: 15
```

Is this expected? If so, maybe we can disable them.

**Comment by whchung** [comment]
@pfultz2 none of these tests are expected to fail. I guess it's an issue in the Jenkins server. I'll need to hold it for a couple of days before I have access to the server next week.

**Comment by kknox** [comment]
I believe these unit tests are failing, because for some reason they are emitting gfx701 isa, and our test machines don't have that.

```
Command Output (stdout):
--
Generating AMD GCN kernel failed in llc for target: gfx701
```

**Comment by yxsamliu** [comment]
We can log these failures and temporarily add XFAIL to these tests and enable the unit test. At least we can prevent future regressions.
After we fix those failures we will remove XFAIL from them.

**Comment by whchung** [comment]
@scchan you've fixed / disabled intermittent failing cases. Do you think it's a good idea to merge this PR now?

**Comment by scchan** [comment]
@whchung I was planning to enable that.  This PR couldn't be built by CI some reason (maybe it's too old) so it's probably better to close this and resubmit

**Comment by kknox** [comment]
We can manually kick off a build and see if it flips to green.  

I think jenkins has a bug where if the source branch, (jenkins-test) is in the same repo as the target branch (clang_tot_upgrade), it doesn't list it on the jenkins dashboard as a PR.  You have to go to the branch name and click 'build now'.  The easiest way is to just click on the red x and you will be taken to the jenkins branch dashboard.

**Comment by kknox** [comment]
The branch does fail almost immediately; i think the branch should be rebased on top of clang_tot_upgrade, because it looks like it is using an old jenkinsfile to build.

**Comment by whchung** [comment]
Close this PR as `Jenkinsfile` here is already obsolete.

**Comment by whchung** [comment]
@kknox I've closed this PR. Since you are more well-versed in `Jenkinsfile` and CI configuration, could you help submit a new one?

**Comment by pfultz2** [comment]
So merged in the latest.

**Comment by whchung** [comment]
@kknox could you help kickstart the build for this PR and see how it goes?

**Comment by pfultz2** [comment]
Its building.

**Comment by whchung** [comment]
There are quite a few failures in `make test`. Those failing tests at a first glimpse are mostly due to new changes in upstream LLVM regarding to `syncscope`.

I think it'll be better to hold this PR a bit more, before we have a clean result of `make test`. Thoughts? @pfultz2 @kknox @scchan

**Comment by kknox** [comment]
If you merge now, you will be living with a red-X's on all commits and PR's until the issue is fixed; probably not worth it.  This branch should be re-based periodically and rerun so that you know when tests pass, and then merged in.

**Comment by scchan** [comment]
We should give this another kick again since the test suite has been cleaned up recently.
It seems CI doesn't merge this with latest clang_to_upgrade automatically before a build and someone has to do a merge manually, is that a bug in CI?

**Comment by kknox** [comment]
I'm not 100% sure (I'll have to find documentation), but i think CI will stop automagically merging with HEAD after it sees MERGE commits into the branch.  Instead of rebasing, I think Paul used merge commands to synced with CTU, which excludes trivial fast-forward merges in the future.  

I'm sure Paul can easily get this to build again, github thinks there are no merge conflicts.

**Comment by kknox** [comment]
Still fails
**First failiure:**
```
FAIL: HCC :: Unit/AMDGPU/register-control.cpp (16 of 758)
******************** TEST 'HCC :: Unit/AMDGPU/register-control.cpp' FAILED ********************
Script:
--

Exit Code: 1

Command Output (stderr):
--
llvm-dis: Too many positional arguments specified!
Can specify at most 1 positional arguments: 
See: /var/jenkins/workspace/penCompute_hcc_jenkins-test-D2OIQ5PMZSHHUKW73C4YWG32RITXW3YJFM2LB6NJAPIUZTKUU5CQ/build/release/compiler/bin/llvm-dis -help
```
**Test report:**
```
********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 254.98s
********************
Failing Tests (7):
    HCC :: Unit/AMDGPU/register-control.cpp
    HCC :: Unit/AsyncPFE/async_av_dependent7.cpp
    HCC :: Unit/AsyncPFE/async_av_dependent8.cpp
    HCC :: Unit/Codegen/indirect-func-arg.cpp
    HCC :: Unit/DynamicTileStatic/test11.cpp
    HCC :: Unit/GridLaunch/register-control.cpp
    HCC :: Unit/HC/completion_future_is_ready.cpp

  Expected Passes    : 719
  Expected Failures  : 32
  Unexpected Failures: 7
```

**Comment by whchung** [comment]
this PR is replaced with #469

**Pull request closed without merging**
