### PR TITLE
Use rocm cmake modules

### PR DESCRIPTION
**Pull request by pfultz2**
This is still a WIP. This will use the rocm cmake modules. The installation will now install the symlinks instead of doing it in the pre/post packaging script, which means the installation will be the same as installing with the package.

### CODE REVIEW

**Comment by whchung** [comment]
@pfultz2 could you check the errors in Jenkins build? even though hcc is successfully built and packaged, but it seems to have something related to the changes in this PR so the package isn't usable in a Docker container. Also, could you help rebase the PR so it aligns with the tip of `clang_tot_upgrade` branch?

**Comment by whchung** [comment]
@pfultz2 could you remove submodule changes from this PR? i believe only CMake files within `hcc` are really changed, and other submodules shall be as-is.

**Comment by pfultz2** [comment]
I didn't change the submodules.

**Comment by whchung** [comment]
@pfultz2 you may add `git add clang compiler lld` unknowingly. or could you rebase this PR with the current tip?

**Comment by pfultz2** [comment]
I just needed to merge from upstream. Now there is no conflicts.

**Comment by pfultz2** [comment]
But it shows that the submodules are changed.

**Comment by pfultz2** [comment]
Ok, now they are synced with clang_tot_upgrade

**Pull request closed without merging**
