### PR TITLE
Don't use hcc-config for unit tests

### PR DESCRIPTION
**Pull request by vsytch**
This is a follow up change to https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/100.

### CODE REVIEW

**Review by scchan — COMMENTED** [review]
LGTM but before I approve this, you'll have to submit a PR to pick up the clang driver change.

**Review by scchan — CHANGES_REQUESTED** [review]
- there's a conflict with clang so please resolve it
- don't you need to update cmakefile for compiling the hcc RT files?

**Comment by vsytch** [comment]
I checked our cmake files, we don't add -hc when linking mcwamp and hc_am, so this change doesn't affect them.

**Comment by scchan** [comment]
then where is fno-hcc-lib-link needed?

**Comment by vsytch** [comment]
It's not needed anywhere in the build files as of right now.

**Comment by scchan** [comment]
I'm confused so we don't need the fno-hcc-lib-link option at all?

**Comment by vsytch** [comment]
I guess we can get rid of it for now them? But then we don't give the user an option if they don't want to link to libmcwamp/libhc_am for whatever reason.

**Comment by scchan** [comment]
yes, please submit another PR to remove it

**Comment by scchan** [comment]
some of the unit tests failed, a few of them are probably regressions from other commits, could you take a look at these ones?

    HCC :: Unit/RawGenericPointer/array_add_am14.cpp
    HCC :: Unit/RawGenericPointer/array_add_am15.cpp
    HCC :: Unit/RawGenericPointer/array_add_am16.cpp
    HCC :: Unit/RawGenericPointer/array_add_am9.cpp

**Comment by scchan** [comment]
ignore my previous comment, I don't think this PR is causing those regressions

**Review by scchan — APPROVED** [review]

**Pull request merged**
