### PR TITLE
Enable jenkins test

### PR DESCRIPTION
**Pull request by scchan**

### CODE REVIEW

**Comment by kknox** [comment]
This PR used to fail hundreds of tests, but the latest runs show that the first test hangs, and is eventually killed by jenkins.  An improvement.

**Comment by whchung** [comment]
@scchan @kknox this PR is now having pass check mark

**Comment by whchung** [comment]
we have only 2 outstanding failures:

```
Failing Tests (2):
    HCC :: Unit/Codegen/separate.cpp
    HCC :: Unit/DynamicTileStatic/test11.cpp
```

- `test11.cpp` should be fixed by @scchan 's recent commit in `ROCm-Device-Libs`.
- `separate.cpp` have to be looked into. it's not failing on my box.

**Comment by whchung** [comment]
@scchan @kknox in #500 I made sure `make test` is passing on my local box. let's see how Jenkins say

**Comment by whchung** [comment]
@scchan @kknox shall we merge this PR?

```
Testing Time: 2305.40s
  Expected Passes    : 735
  Expected Failures  : 32
```

**Comment by scchan** [comment]
@whchung Let's do that, could you review and approve?

**Review by whchung — APPROVED** [review]

**Pull request merged**
