### PR TITLE
Fix HCC Unit Tests with FCS enabled

### PR DESCRIPTION
**Pull request by aaronenyeshi**
* Update the clang submodule to include https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/173
* Disable statement_recursion AMP test. 
  * This already has been disabled with XFAIL, but we need to disable completely because FCS enabled unit test runs hang. So disable completely with macro.

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
With FCS enabled on HCC Unit tests, this PR results:
```
********************
Testing Time: 621.54s
********************
Failing Tests (5):
    HCC :: Unit/HSA/printf.cpp
    HCC :: Unit/HSA/printf_error_check.cpp
    HCC :: Unit/HSA/printf_excess_args.cpp
    HCC :: Unit/HSA/printf_supported_types.cpp
    HCC :: Unit/Overload/amp_lambda_or_pfe_in_a_cpu_or_cpu_elided_function_or_lambda.cpp

  Expected Passes    : 692
  Expected Failures  : 35
  Unexpected Failures: 5
```

**Review by scchan — DISMISSED** [review]
just delete the recursion test

**Comment by aaronenyeshi** [comment]
@scchan  I've removed the test, thanks

**Comment by scchan** [comment]
I think all the failing tests have been disabled, closing this.

**Pull request closed without merging**
