### PR TITLE
Remove the runtime plugin infrastructure

### PR DESCRIPTION
**Pull request by scchan**
The runtime plugin was there to support multiple runtime backends in the past.  Since we've only
supported the ROCR runtime backend since ROCm 1.x and there has been no support for other runtime backends, remove the runtime plugin clutter.

### CODE REVIEW

**Comment by jeffdaily** [comment]
What is the rationale for keeping libhc_am.so as a separate library?

**Comment by scchan** [comment]
> What is the rationale for keeping libhc_am.so as a separate library?
I think some of the apps and libs explicitly link to libhc_am.so.  If I remove libhc_am.so then I'll have to go and update all the libs affected.  Logically it makes sense to remove libhc_am.so as well but I just don't have the time to go through that at the moment.

**Review by ssahasra — APPROVED** [review]
LGTM. Can we now have another patch that removes the lib/cpu directory?

**Comment by scchan** [comment]
> LGTM. Can we now have another patch that removes the lib/cpu directory?

It's already gone

**Pull request merged**
