### PR TITLE
Printf - Using Host Coherent mem for printf buffer

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Moving towards coherent memory for printf buffer. right now, the strings are created on host memory, and we only pass around the pointers to them. Later we want to keep the strings on coherent memory.

Passes tests/Unit/HSA/printf.cpp testcase.

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
********************
Testing Time: 195.72s
********************
Failing Tests (5):
    HCC :: Unit/AmpMath/amp_math_tgamma_precise_math.cpp
    HCC :: Unit/AsyncPFE/async_av_dependent7.cpp
    HCC :: Unit/HC/hc_atomic_min_global.cpp
    HCC :: Unit/HC/multi_acc2.cpp
    HCC :: Unit/HC/pinned_vector.cpp

  Expected Passes    : 721
  Expected Failures  : 32
  Unexpected Failures: 5

**Comment by aaronenyeshi** [comment]
Not sure about the other test failures, but I ran it again and got this:
Failing Tests (6):
    HCC :: Unit/AcceleratorViewCopy/copy_coherency.cpp
    HCC :: Unit/AsyncPFE/async_av_dependent8.cpp
    HCC :: Unit/AsyncPFE/async_av_independent4.cpp
    HCC :: Unit/HC/multi_acc.cpp
    HCC :: Unit/HC/multi_acc2.cpp
    HCC :: Unit/HC/pinned_vector.cpp

  Expected Passes    : 720
  Expected Failures  : 32
  Unexpected Failures: 6

Don't think its related to my hc_printf.cpp changes.

**Comment by aaronenyeshi** [comment]
Actually just updated my HCC to latest, and this is make test results:
Failing Tests (2):
    HCC :: Unit/DynamicTileStatic/test11.cpp
    HCC :: Unit/HC/multi_acc2.cpp

  Expected Passes    : 726
  Expected Failures  : 32
  Unexpected Failures: 2

**Comment by whchung** [comment]
@aaronenyeshi the PR looks good to me. need inputs from @scchan as he is the original author.

**Pull request merged**
