### PR TITLE
[Config] revise submodule configuration

### PR DESCRIPTION
**Pull request by aaronenyeshi**

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
I'm confused with the Jenkins PR failure

**Comment by aaronenyeshi** [comment]
```
ERROR: Failed to copy artifacts from RadeonOpenCompute/hcc/PR-466 with filter: archive/**/*.deb, docker/dockerfile-*
Finished: FAILURE
```
Not sure how HIP/PR-92 failed here.

**Comment by aaronenyeshi** [comment]
@kknox believes that this issue may be due to old PR recently merged: https://github.com/ROCm-Developer-Tools/HIP/pull/161 which may have paths wrong. So lets hold this PR until later

**Comment by aaronenyeshi** [comment]
Seems that HIP master build is down on Jenkins: http://hsautil.amd.com/job/ROCm-Developer-Tools/job/HIP/job/master/

**Comment by whchung** [comment]
@kknox  from the error at:

```
http://hsautil.amd.com/job/ROCm-Developer-Tools/job/HIP/job/master/107/console
```

it shows:

```
+ docker build -t hcc-test-RadeonOpenCompute-hcc-PR-466-9/hcc:107 -f dockerfile-hcc-lc-ubuntu-16.04 .
invalid argument "hcc-test-RadeonOpenCompute-hcc-PR-466-9/hcc:107" for t: invalid reference format: repository name must be lowercase
```

I believe it could be a build script issue?

**Comment by aaronenyeshi** [comment]
Also, updating clang to include the SLP Vectorizer FE removal fix. 
https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/84

**Comment by scchan** [comment]
@kknox  For this PR, I've enabled the optional HIP integration test but the HIP build failed to start.  Based on the error message, it looks like the hip jenkins script needs to convert the `org` string to lower case? https://github.com/ROCm-Developer-Tools/HIP/blob/master/Jenkinsfile#L120

**Comment by kknox** [comment]
Will look into it now.

**Comment by kknox** [comment]
You can see with my [test build](http://hsautil.amd.com/job/RadeonOpenCompute/job/hcc/view/change-requests/job/PR-466/) that this PR passes hip integration testing.  This was building this PR against my fork of HIP synced with master.

My patch for HiP build is in-flight: https://github.com/ROCm-Developer-Tools/HIP/pull/192

**Comment by aaronenyeshi** [comment]
@whchung @scchan Ready to be integrated?

**Pull request merged**
