### PR TITLE
fix several lock guards

### PR DESCRIPTION
**Pull request by scchan**

### CODE REVIEW

**Review by whchung — APPROVED** [review]
LGTM. + @bensander

**Comment by whchung** [comment]
@scchan seems the build server is down?

**Comment by scchan** [comment]
@whchung I rebooted the machine that the jenkins slave was running on.  I restarted the build again.

**Comment by whchung** [comment]
@scchan in any case this commit should definitely be cherry-picked into `roc-1.7.x` release branch.

**Review by whchung — APPROVED** [review]
thanks @scchan . + @bensander for awareness. this is pretty deep.

**Pull request merged**
